# Copyright (C) 2025, RTE (http://www.rte-france.com)
# SPDX-License-Identifier: Apache-2.0

sonar.projectKey=seapath_python3-setup-ovs
sonar.organization=seapath

sonar.sources=setup_ovs
sonar.tests=tests

sonar.python.version=3.9, 3.10, 3.11, 3.12, 3.13
sonar.python.coverage.reportPaths=coverage.xml
